version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:latest  # Use the latest version supporting KRaft mode
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  saga-orchestrator:
    build:
      context: ./SagaOrchestrator
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  account-service:
    build:
      context: ./AccountService
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  transaction-service:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  audit-service:
    build:
      context: ./AuditService
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
