version: '3.8'
services:
  kafka:
    image: confluentinc/cp-kafka:latest  # Use the latest version supporting KRaft mode
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: 'broker:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid" 
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  saga-orchestrator:
    build:
      context: ./SagaOrchestrator
      dockerfile: Dockerfile
    ports:
      - "6001:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  account-service:
    build:
      context: ./AccountManager
      dockerfile: Dockerfile
    ports:
      - "6002:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  transaction-service:
    build:
      context: ./TransactionManager
      dockerfile: Dockerfile
    ports:
      - "6003:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  notification-service:
    build:
      context: ./NotificationManager
      dockerfile: Dockerfile
    ports:
      - "6004:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  audit-service:
    build:
      context: ./AuditManager
      dockerfile: Dockerfile
    ports:
      - "6005:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
