apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-manager
  namespace: banking-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-manager
  template:
    metadata:
      labels:
        app: notification-manager
    spec:
      containers:
        - name: notification-manager
          image: notification-manager:latest
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_BROKER
              value: broker:9092

---

apiVersion: v1
kind: Service
metadata:
  name: notification-manager
  namespace: banking-app-dev
spec:
  type: ClusterIP
  selector:
    app: notification-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
