apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-orchestrator
  namespace: banking-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-orchestrator
  template:
    metadata:
      labels:
        app: saga-orchestrator
    spec:
      containers:
        - name: saga-orchestrator
          image: saga-orchestrator:latest
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_BROKER
              value: broker:9092

---

apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator
  namespace: banking-app-dev
spec:
  type: ClusterIP
  selector:
    app: saga-orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
