<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventSourcingCoreModules\Core\Core.csproj" />
    <ProjectReference Include="..\..\EventSourcingCoreModules\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\MediatRActionModules\ActionImplementations\ActionImplementations.csproj" />
    <ProjectReference Include="..\..\MediatRActionModules\ActionModels\ActionModels.csproj" />
    <ProjectReference Include="..\..\DomainModules\InventoryModule\InventoryModule.csproj" />
    <ProjectReference Include="..\..\DomainModules\OrderModule\OrderModule.csproj" />
    <ProjectReference Include="..\..\DomainModules\PaymentModule\PaymentModule.csproj" />
    <ProjectReference Include="..\..\DomainModules\ShippingModule\ShippingModule.csproj" />
  </ItemGroup>

</Project>
